Repository studiometa/ui, pull requests merged in 2024-05, with the labels that each got.

#202 Configure Renovate
  .github/renovate.json
Labels: renovate

#204 Update dependency @iconify-json/octicon to v1.1.54
  package-lock.json
Labels: renovate

#205 Update dependency studiometa/twig-toolkit to v1.3.6
  composer.lock
  packages/docs/.symfony/composer.lock
Labels: renovate

#206 Update dependency vitepress to v1.1.4
  package-lock.json
Labels: renovate

#207 Update symfony packages
  packages/docs/.symfony/composer.lock
Labels: renovate

#217 Lock file maintenance
  composer.lock
  package-lock.json
  packages/docs/.symfony/composer.lock
Labels: renovate

#214 Update dependency twig/twig to v3.10.2
  composer.lock
  packages/docs/.symfony/composer.lock
Labels: renovate

#218 Update dependency twig/twig to v3.10.3
  composer.lock
  packages/docs/.symfony/composer.lock
Labels: renovate

#220 Lock file maintenance
  package-lock.json
Labels: renovate

#219 Update dependency vitepress to v1.2.2
  package-lock.json
Labels: renovate

#222 Lock file maintenance
  composer.lock
  package-lock.json
Labels: renovate

#198 [Feature] Demo: Navbar component
  CHANGELOG.md
  packages/docs/demos/Navbar/index.md
  packages/docs/demos/Navbar/stories/app.css
  packages/docs/demos/Navbar/stories/app.js
  packages/docs/demos/Navbar/stories/app.twig
Labels: documentation

#215 Update dependency unplugin-icons to ^0.19.0
  package-lock.json
  packages/docs/package.json
Labels: renovate

#209 Update dependency esbuild to ^0.21.0
  package-lock.json
  package.json
Labels: renovate

#201 [Feature] Icons update and `IconList` molecule
  CHANGELOG.md
  packages/docs/components/atoms/Button/twig-api.md
  packages/docs/components/atoms/IconInline/index.md
  packages/docs/components/atoms/IconInline/stories/app.twig
  packages/docs/components/atoms/IconInline/twig-api.md
  packages/docs/components/atoms/IconInlineImg/index.md
  packages/docs/components/atoms/IconInlineImg/stories/app.twig
  packages/docs/components/atoms/IconInlineImg/twig-api.md
  packages/docs/components/molecules/IconList/examples.md
  packages/docs/components/molecules/IconList/index.md
  packages/docs/components/molecules/IconList/stories/app.twig
  packages/docs/components/molecules/IconList/twig-api.md
  packages/ui/atoms/Button/Button.twig
  packages/ui/atoms/Icon/IconInline.twig
  packages/ui/atoms/Icon/IconInlineImg.twig
  packages/ui/molecules/IconList/IconList.twig
  packages/ui/svg/at.svg
  packages/ui/svg/copy.svg
  packages/ui/svg/facebook.svg
  packages/ui/svg/globe.svg
  packages/ui/svg/instagram.svg
  packages/ui/svg/link.svg
  packages/ui/svg/linkedin.svg
  packages/ui/svg/mail.svg
  packages/ui/svg/phone.svg
  packages/ui/svg/pinterest.svg
  packages/ui/svg/tiktok.svg
  packages/ui/svg/twitter.svg
  packages/ui/svg/whatsapp.svg
  packages/ui/svg/x.svg
Labels: enhancement

#225 Update dependency esbuild to v0.21.3
  package-lock.json
Labels: renovate

#226 Update dependency oxlint to v0.4.1
  package-lock.json
Labels: renovate

#227 Update dependency esbuild to v0.21.4
  package-lock.json
Labels: renovate

#228 Update dependency @vueuse/components to v10.10.0
  package-lock.json
Labels: renovate

#229 Update dependency @vueuse/core to v10.10.0
  package-lock.json
Labels: renovate

#216 Update dependency unplugin-vue-components to ^0.27.0
  package-lock.json
  packages/docs/package.json
Labels: renovate

#230 Update dependency oxlint to v0.4.2
  package-lock.json
Labels: renovate
